### PR TITLE
lltop to torque job mapping.

### PR DESCRIPTION
**Pull request by dragz**
This is a simple python script to map nodes which put the most pressure on the lustre servers to torque jobs.
I've put it in a contrib/ subdir to separate it from the main lltop.

Thanks for a great tool!  It saved us a lot of time when somebody suddenly started to bog down our lustre filesystem.

### CODE REVIEW

**Comment by jhammond** [comment]
I'm fine with this but the file names are a bit generic. Do you mind renaming them to contrib/torque/{README.md,lustrejobtop.py}?

**Comment by dragz** [comment]
Sure no, problem. New pull request arriving shortly...

**Comment by dragz** [comment]
I'm kind of a github novice, can you pull my last commit?

**Comment by jhammond** [comment]
Done. Thanks!

**Pull request merged**
